// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package order

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID          int32              `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	ServiceType pgtype.Text        `json:"service_type"`
	Status      pgtype.Text        `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
