// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package order

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	DeleteOrder(ctx context.Context, id int32) error
	GetOrderByID(ctx context.Context, id int32) (Order, error)
	ListOrdersByUser(ctx context.Context, userID pgtype.UUID) ([]Order, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
